old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        mailer:
            connection:       default
            exchange_options: { name: 'mailer', type: direct }
    consumers:
        mailer:
            connection:       default
            exchange_options: { name: 'mailer', type: direct }
            queue_options:    { name: 'mailer' }
            callback:         App\Consumer\MailerConsumer
